# Generated by Django 5.0.2 on 2024-12-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healtho_pro_user', '0002_initial'),
        ('interoperability', '0001_initial'),
        ('pro_hospital', '0002_initial'),
        ('pro_laboratory', '0001_initial'),
        ('pro_pharmacy', '0001_initial'),
        ('pro_universal_data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labpatientreceipts',
            name='medicines',
            field=models.ManyToManyField(blank=True, to='pro_pharmacy.patientmedicine'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='packages',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatientpackages'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='payment_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.paymentfor'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='payments',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatientpayments'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='rooms',
            field=models.ManyToManyField(blank=True, to='pro_hospital.iproombooking'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='services',
            field=models.ManyToManyField(blank=True, to='pro_hospital.patientservices'),
        ),
        migrations.AddField(
            model_name='labpatientrefund',
            name='packages',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatientpackages'),
        ),
        migrations.AddField(
            model_name='labpatientrefund',
            name='refund_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpaymentmodetype'),
        ),
        migrations.AddField(
            model_name='labpatienttests',
            name='LabGlobalTestId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='labpatienttests',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessaddresses'),
        ),
        migrations.AddField(
            model_name='labpatienttests',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='labpatienttests',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabteststatus'),
        ),
        migrations.AddField(
            model_name='labpatientrefund',
            name='tests',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='tests',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labpatientpackages',
            name='lab_tests',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labpatientfixedreporttemplate',
            name='LabPatientTestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labdrauthorizationremarks',
            name='LabPatientTestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_dr_authorization_remarks', to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labdrauthorization',
            name='LabPatientTestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_dr_authorization', to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labpatientwordreporttemplate',
            name='LabPatientTestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labpatientwordreporttemplate',
            name='pages',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatientwordreporttemplatepagewisecontent'),
        ),
        migrations.AddField(
            model_name='labphlebotomist',
            name='LabPatientTestID',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='phlebotomist', to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labreportstemplates',
            name='LabGlobalTestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='labreportstemplates',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='labreportstemplates',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabreporttype'),
        ),
        migrations.AddField(
            model_name='labfixedparametersreporttemplate',
            name='LabReportsTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labreportstemplates'),
        ),
        migrations.AddField(
            model_name='labdoctors',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labshift'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labbranch'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='branches',
            field=models.ManyToManyField(blank=True, to='healtho_pro_user.businessaddresses'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='employement_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.labemploymenttype'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabstaffgender'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='pro_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labshift'),
        ),
        migrations.AddField(
            model_name='labphlebotomist',
            name='collected_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='collected_labphlebotomists', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labphlebotomist',
            name='received_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_labphlebotomists', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientwordreporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientwordreporttemplate',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labpatientwordreporttemplate_lastupdatedby', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientrefund',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientpackages',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientfixedreporttemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labpatientfixedreporttemplate',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labpatientfixedreporttemplate_lastupdatedby', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labmenuaccess',
            name='lab_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labglobalpackages',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labdrauthorizationremarks',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labdrauthorization',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labdoctors',
            name='marketing_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labappointmentforpatient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labappointmentforpatient',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_appointment_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='defaultsfordepartments',
            name='lab_technician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='lab_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='bulkmessaginghistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='lab_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffattendancedetails',
            name='attendance_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.labstaffattendancestatus'),
        ),
        migrations.AddField(
            model_name='labstaffattendancedetails',
            name='lab_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffdefaultbranch',
            name='default_branch',
            field=models.ManyToManyField(blank=True, to='healtho_pro_user.businessaddresses'),
        ),
        migrations.AddField(
            model_name='labstaffdefaultbranch',
            name='lab_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffidentificationdetails',
            name='labstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffidentificationdetails',
            name='salary_payment_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.salarypaymentmodes'),
        ),
        migrations.AddField(
            model_name='labstaffjobdetails',
            name='labstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffjobdetails',
            name='payment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.marketingpaymenttype'),
        ),
        migrations.AddField(
            model_name='labstaffleaverequest',
            name='lab_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffleaverequest',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.leavetypes'),
        ),
        migrations.AddField(
            model_name='labstaffleaverequest',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.leavestatus'),
        ),
        migrations.AddField(
            model_name='labstaffloginaccess',
            name='lab_staff_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffpayroll',
            name='lab_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffpayroll',
            name='payment_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.marketingpaymenttype'),
        ),
        migrations.AddField(
            model_name='labstaffpersonaldetails',
            name='blood_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.universalbloodgroups'),
        ),
        migrations.AddField(
            model_name='labstaffpersonaldetails',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.city'),
        ),
        migrations.AddField(
            model_name='labstaffpersonaldetails',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.country'),
        ),
        migrations.AddField(
            model_name='labstaffpersonaldetails',
            name='labstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffpersonaldetails',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.universalmaritalstatus'),
        ),
        migrations.AddField(
            model_name='labstaffpersonaldetails',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.state'),
        ),
        migrations.AddField(
            model_name='labstaffprintsettings',
            name='lab_staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaffrole'),
        ),
        migrations.AddField(
            model_name='labstaffrolepermissions',
            name='lab_menu_access_list',
            field=models.ManyToManyField(blank=True, to='pro_universal_data.ulabmenus'),
        ),
        migrations.AddField(
            model_name='labstaffrolepermissions',
            name='lab_staff_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaffrole'),
        ),
        migrations.AddField(
            model_name='labstaffvehicledetails',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.universalfueltypes'),
        ),
        migrations.AddField(
            model_name='labstaffvehicledetails',
            name='labstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labstaffvehicledetails',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.universalvehicletypes'),
        ),
        migrations.AddField(
            model_name='labtechnicianremarks',
            name='LabPatientTestID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lab_technician_remarks', to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labtechnicianremarks',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labtechnicians',
            name='LabPatientTestID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labtechnician', to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='labtechnicians',
            name='access',
            field=models.ManyToManyField(blank=True, related_name='accessible_labtechnicians', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtechnicians',
            name='consulting_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdoctors'),
        ),
        migrations.AddField(
            model_name='labtechnicians',
            name='report_created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='report_created_labtechnicians', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labwordreporttemplate',
            name='LabReportsTemplate',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labreportstemplates'),
        ),
        migrations.AddField(
            model_name='labwordreporttemplate',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='labwordreporttemplate',
            name='pages',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labwordreporttemplatepagewisecontent'),
        ),
        migrations.AddField(
            model_name='labstaff',
            name='lab_working_days',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labworkingdays'),
        ),
        migrations.AddField(
            model_name='labdoctors',
            name='lab_working_days',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labworkingdays'),
        ),
        migrations.AddField(
            model_name='letterheadsettings',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='letterheadsettings',
            name='default_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabfonts'),
        ),
        migrations.AddField(
            model_name='machineintegrationmodel',
            name='machine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.machine'),
        ),
        migrations.AddField(
            model_name='marketingexecutivelocationtracker',
            name='lab_staff',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='marketingexecutivetargets',
            name='labstaff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='marketingexecutivetargets',
            name='target_duration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.marketingtargetdurations'),
        ),
        migrations.AddField(
            model_name='marketingexecutivetargets',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.marketingtargettypes'),
        ),
        migrations.AddField(
            model_name='marketingexecutivevisits',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_created_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='marketingexecutivevisits',
            name='lab_staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='marketingexecutivevisits',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visit_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='marketingexecutivevisits',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.marketingvisitstatus'),
        ),
        migrations.AddField(
            model_name='marketingexecutivevisits',
            name='visit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.marketingvisittypes'),
        ),
        migrations.AddField(
            model_name='messaginglogs',
            name='messaging_send_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_universal_data.messagingsendtype'),
        ),
        migrations.AddField(
            model_name='messaginglogs',
            name='messaging_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_universal_data.messagingvendors'),
        ),
        migrations.AddField(
            model_name='labglobaltests',
            name='methodology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_laboratory.methodology'),
        ),
        migrations.AddField(
            model_name='patient',
            name='ULabPatientAge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpatientage'),
        ),
        migrations.AddField(
            model_name='patient',
            name='attender_relationship_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpatientattendertitles'),
        ),
        migrations.AddField(
            model_name='patient',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessaddresses'),
        ),
        migrations.AddField(
            model_name='patient',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpatientgender'),
        ),
        migrations.AddField(
            model_name='patient',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patient',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.companyworkpartnership'),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.patienttype'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient', to='pro_laboratory.labdoctors'),
        ),
        migrations.AddField(
            model_name='patient',
            name='title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpatienttitles'),
        ),
        migrations.AddField(
            model_name='mtpinfo',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='labpatienttests',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='labpatientrefund',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='labpatientreceipts',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='labpatientpackages',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='labpatientinvoice',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='labappointmentforpatient',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_appointment', to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='homeservice',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='familygenetichistory',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='appointmentdetails',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='activitylogs',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='patientappointmentwithdoctor',
            name='appointment_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.prodoctorappointmentslot'),
        ),
        migrations.AddField(
            model_name='patientappointmentwithdoctor',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.prodoctorconsultation'),
        ),
        migrations.AddField(
            model_name='patientappointmentwithdoctor',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='patientappointmentwithdoctor',
            name='pay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpaymentmodetype'),
        ),
        migrations.AddField(
            model_name='patientappointmentwithdoctor',
            name='pro_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.prodoctor'),
        ),
        migrations.AddField(
            model_name='pndtresults',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='prenatalscreening',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='printtemplate',
            name='print_template_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.printtemplatetype'),
        ),
        migrations.AddField(
            model_name='printdatatemplate',
            name='print_template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.printtemplate'),
        ),
        migrations.AddField(
            model_name='printtestreportsettings',
            name='client',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='privilegecardmembers',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpatientgender'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='card_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecardfor'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='card_holder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecardmembers'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_holder_created_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='duration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.timedurationtypes'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='card_holder_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='plan_period_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='patient',
            name='privilege_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecardmemberships'),
        ),
        migrations.AddField(
            model_name='privilegecards',
            name='card_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecardfor'),
        ),
        migrations.AddField(
            model_name='privilegecards',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='privilegecards',
            name='duration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.timedurationtypes'),
        ),
        migrations.AddField(
            model_name='privilegecards',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='privilegecards',
            name='plan_period_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.availabilityperiod'),
        ),
        migrations.AddField(
            model_name='privilegecardmemberships',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecards'),
        ),
        migrations.AddField(
            model_name='privilegecardsapplicablebenefits',
            name='benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.privilegecardbenefits'),
        ),
        migrations.AddField(
            model_name='privilegecardsapplicablebenefits',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecards'),
        ),
        migrations.AddField(
            model_name='privilegecardslabdepartmentsbenefits',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecards'),
        ),
        migrations.AddField(
            model_name='privilegecardslabdepartmentsbenefits',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='privilegecardslabtestbenefits',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecards'),
        ),
        migrations.AddField(
            model_name='privilegecardslabtestbenefits',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='privilegecardsmembershipapplicablebenefits',
            name='benefit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.privilegecardbenefits'),
        ),
        migrations.AddField(
            model_name='privilegecardsmembershipapplicablebenefits',
            name='membership',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.privilegecardmemberships'),
        ),
        migrations.AddField(
            model_name='proceduresperformed',
            name='clinic_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessaddresses'),
        ),
        migrations.AddField(
            model_name='proceduresperformed',
            name='doctors',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labdoctors'),
        ),
        migrations.AddField(
            model_name='proceduresperformed',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='recommendedtests',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='referralamountfordoctor',
            name='lab_test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='referralamountfordoctor',
            name='referral_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdoctors'),
        ),
        migrations.AddField(
            model_name='sendandsavewhatsappsmsdata',
            name='messaging_send_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_universal_data.messagingsendtype'),
        ),
        migrations.AddField(
            model_name='sendandsavewhatsappsmsdata',
            name='mwa_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.messagingtemplates'),
        ),
        migrations.AddField(
            model_name='sendsmsdata',
            name='messaging_send_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pro_universal_data.messagingsendtype'),
        ),
        migrations.AddField(
            model_name='sendsmsdata',
            name='sms_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.messagingtemplates'),
        ),
        migrations.AddField(
            model_name='messaginglogs',
            name='sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sendsmsdata'),
        ),
        migrations.AddField(
            model_name='sourcinglabletterheadsettings',
            name='default_font',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabfonts'),
        ),
        migrations.AddField(
            model_name='sourcinglabpatientreportuploads',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='sourcinglabpatientreportuploads',
            name='tests',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labpatienttests'),
        ),
        migrations.AddField(
            model_name='sourcinglabpayments',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='sourcinglabregistration',
            name='acceptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acceptor', to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='sourcinglabregistration',
            name='initiator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initiator', to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='sourcinglabregistration',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.sourcinglabtype'),
        ),
        migrations.AddField(
            model_name='sourcinglabpayments',
            name='sourcing_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='sourcinglabletterheadsettings',
            name='sourcing_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='patient',
            name='referral_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='labpatienttests',
            name='sourcing_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='labglobaltests',
            name='sourcing_lab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='sourcinglabrevisedtestprice',
            name='LabGlobalTestId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='sourcinglabrevisedtestprice',
            name='sourcing_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='sourcinglabteststracker',
            name='sourcing_lab',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sourcinglabregistration'),
        ),
        migrations.AddField(
            model_name='labtechnicians',
            name='ultrasound_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.tpaultrasound'),
        ),
        migrations.AddField(
            model_name='tpaultrasoundconfig',
            name='lab_tpa_secret_keys',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interoperability.labtpasecretkeys'),
        ),
        migrations.AddField(
            model_name='tpaultrasound',
            name='images',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.tpaultrasoundimages'),
        ),
        migrations.AddField(
            model_name='userpermissionsaccess',
            name='lab_staff',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='userpermissionsaccess',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='pro_universal_data.userpermissions'),
        ),
        migrations.AddField(
            model_name='whatsappconfigurations',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='whatsappmessaginglogs',
            name='messaging_send_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_universal_data.messagingsendtype'),
        ),
        migrations.AddField(
            model_name='whatsappmessaginglogs',
            name='messaging_vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.messagingvendors'),
        ),
        migrations.AddField(
            model_name='whatsappmessaginglogs',
            name='sms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.sendandsavewhatsappsmsdata'),
        ),
    ]
