# Generated by Django 5.0.2 on 2024-12-27 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labdoctors',
            name='is_department_default',
        ),
        migrations.DeleteModel(
            name='DefaultConsultingDoctor',
        ),
    ]
