# Generated by Django 5.0.2 on 2024-12-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0003_remove_labdoctors_is_department_default_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labpatienttests',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
