# Generated by Django 5.0.2 on 2025-01-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0004_labpatienttests_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
