# Generated by Django 5.0.2 on 2025-01-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0005_alter_patient_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='mr_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
