# Generated by Django 5.0.2 on 2025-01-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0006_alter_patient_mr_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='visit_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
