# Generated by Django 5.0.2 on 2025-01-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0008_processingmachine_datafromprocessingmachine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labwordreporttemplate',
            name='pages',
        ),
        migrations.DeleteModel(
            name='LabWordReportTemplatePageWiseContent',
        ),
    ]
