# Generated by Django 5.0.2 on 2025-01-08 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0009_remove_labwordreporttemplate_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labpatientwordreporttemplate',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='labpatientwordreporttemplate',
            name='header',
        ),
        migrations.RemoveField(
            model_name='labpatientwordreporttemplate',
            name='rtf_content_header',
        ),
        migrations.RemoveField(
            model_name='labwordreporttemplate',
            name='header',
        ),
        migrations.DeleteModel(
            name='LabPatientWordReportTemplatePageWiseContent',
        ),
    ]
