# Generated by Django 5.0.2 on 2025-01-08 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0010_remove_labpatientwordreporttemplate_pages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machineintegrationmodel',
            name='machine',
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='MachineIntegrationModel',
        ),
    ]
