# Generated by Django 5.0.2 on 2025-01-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0011_remove_machineintegrationmodel_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labfixedparametersreporttemplate',
            name='round_to_decimals',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='labfixedparametersreporttemplate',
            name='to_display',
            field=models.BooleanField(default=True),
        ),
    ]
