# Generated by Django 5.0.2 on 2025-01-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0012_labfixedparametersreporttemplate_round_to_decimals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicians',
            name='has_machine_integration',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
