# Generated by Django 5.0.2 on 2025-01-15 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0013_labtechnicians_has_machine_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='labfixedparametersreporttemplate',
            name='display_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
