# Generated by Django 5.0.2 on 2025-01-16 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0014_labfixedparametersreporttemplate_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labfixedparametersreporttemplate',
            old_name='display_name',
            new_name='normal_ranges_display',
        ),
    ]
