# Generated by Django 5.0.2 on 2025-01-16 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_laboratory', '0015_rename_display_name_labfixedparametersreporttemplate_normal_ranges_display'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtechnicians',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
