urls_with_models = {

    #accounts
    "/api/accounts/lab_expenses": {"app_name": "accounts", "model_name": "LabExpenses"},
    "/api/accounts/lab_incomes": {"app_name": "accounts", "model_name": "LabIncomes"},
    "/api/accounts/lab_expense_types": {"app_name": "accounts", "model_name": "LabExpenseType"},
    "/api/accounts/lab_paid_to_types": {"app_name": "accounts", "model_name": "LabPaidToType"},
    "/api/accounts/lab_pay_mode_types": {"app_name": "accounts", "model_name": "LabPayModeType"},
    "/api/accounts/lab_to_account_types": {"app_name": "accounts", "model_name": "LabToAccountType"},
    "/api/accounts/lab_income_types": {"app_name": "accounts", "model_name": "LabIncomeType"},


    #healthopro_user
    "/api/user/token": {"app_name": "healtho_pro_user", "model_name": "RefreshToken"},
    "/api/user/users": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/usertypes": {"app_name": "healtho_pro_user", "model_name": "UserType"},
    "/api/user/businessprofiles": {"app_name": "healtho_pro_user", "model_name": "BusinessProfiles"},
    "/api/user/business_timings": {"app_name": "healtho_pro_user", "model_name": "BusinessTimings"},
    "/api/user/business_executive": {"app_name": "healtho_pro_user", "model_name": "BExecutive"},
    "/api/user/business_contactfor": {"app_name": "healtho_pro_user", "model_name": "BContactFor"},
    "/api/user/business_contacts": {"app_name": "healtho_pro_user", "model_name": "BContacts"},
    "/api/user/businesstypes": {"app_name": "healtho_pro_user", "model_name": "BusinessType"},
    "/api/user/business_addresses": {"app_name": "healtho_pro_user", "model_name": "BusinessAddresses"},
    "/api/user/country": {"app_name": "healtho_pro_user", "model_name": "Country"},
    "/api/user/state": {"app_name": "healtho_pro_user", "model_name": "State"},
    "/api/user/city": {"app_name": "healtho_pro_user", "model_name": "City"},
    "/api/user/login_sliders": {"app_name": "healtho_pro_user", "model_name": "ULoginSliders"},
    "/api/user/upro_doctor_specializations": {"app_name": "healtho_pro_user", "model_name": "UProDoctorSpecializations"},

    "/api/user/b_subscription_plan": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionPlan"},
    "/api/user/b_subscription_plan_validity": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionValidity"},
    "/api/user/b_subscriptions_purchased": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionsPurchased"},
    "/api/user/b_subscription_duration": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionDuration"},
    "/api/user/b_subscription_details": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionDetails"},
    "/api/user/b_subscription_billing_invoice": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionBillingInvoice"},
    "/api/user/generate_billing_invoice": {"app_name": "healtho_pro_user", "model_name": "BusinessSubscriptionBillingInvoice"},

    "/api/user/shift": {"app_name": "healtho_pro_user", "model_name": "Shift"},
    "/api/user/consultation": {"app_name": "healtho_pro_user", "model_name": "Consultation"},
    "/api/user/pro_doctors": {"app_name": "healtho_pro_user", "model_name": "ProDoctor"},
    "/api/user/pro_doctor_professional_details": {"app_name": "healtho_pro_user", "model_name": "ProDoctorProfessionalDetails"},
    "/api/user/create": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/login": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/token/refresh": {"app_name": "healtho_pro_user", "model_name": "RefreshToken"},
    "/api/user/otp-login": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/send_otp_to_set_password": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/set_password": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/password_login": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/tenant-info": {"app_name": "healtho_pro_user", "model_name": "UserTenantClient"},
    "/api/user/resend-otp": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/get-nearest": {"app_name": "healtho_pro_user", "model_name": "BusinessProfiles"},
    "/api/user/user_update/<int:pk>": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/user_delete/<int:pk>": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/support_info_tutorials": {"app_name": "healtho_pro_user", "model_name": "SupportInfoTutorials"},
    "/api/user/healthcare_registry_types": {"app_name": "healtho_pro_user", "model_name": "HealthcareRegistryType"},
    "/api/user/permissions": {"app_name": "healtho_pro_user", "model_name": "Permission"},
    "/api/user/delete_group_permissions/<int:pk>": {"app_name": "healtho_pro_user", "model_name": "Group"},
    "/api/user/user_all_permissions/<int:pk>": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser"},
    "/api/user/get_doctors": {"app_name": "healtho_pro_user", "model_name": "HealthOProUser(Doctors)"},

    #inter
    "/api/inter/lab_tpa_secret_keys": {"app_name": "interoperability", "model_name": "LabTpaSecretKeys"},
    "/api/inter/lab_tpa_integrated_secret_keys": {"app_name": "interoperability", "model_name": "LabTpaSecretKeys"},

    #pro_laboratory
    "/api/lab/labstaff": {"app_name": "pro_laboratory", "model_name": "LabStaff"},
    "/api/lab/labdoctors": {"app_name": "pro_laboratory", "model_name": "LabDoctors"},
    "/api/lab/ref_amount_for_doctor": {"app_name": "pro_laboratory", "model_name": "ReferralAmountForDoctor"},
    "/api/lab/patient": {"app_name": "pro_laboratory", "model_name": "Patient"},
    "/api/lab/lab_departments": {"app_name": "pro_laboratory", "model_name": "LabDepartments"},
    "/api/lab/lab_global_tests": {"app_name": "pro_laboratory", "model_name": "LabGlobalTests"},
    "/api/lab/lab_patient_tests": {"app_name": "pro_laboratory", "model_name": "LabPatientTests"},
    "/api/lab/lab_doctor_authorization_approval": {"app_name": "pro_laboratory", "model_name": "LabDrAuthorization"},
    "/api/lab/lab_global_packages": {"app_name": "pro_laboratory", "model_name": "LabGlobalPackages"},
    "/api/lab/lab_patient_packages": {"app_name": "pro_laboratory", "model_name": "LabPatientPackages"},
    "/api/lab/lab_reports_templates": {"app_name": "pro_laboratory", "model_name": "LabReportsTemplates"},
    "/api/lab/lab_employment_types": {"app_name": "pro_laboratory", "model_name": "LabEmploymentType"},
    "/api/lab/lab_branches": {"app_name": "pro_laboratory", "model_name": "LabBranch"},
    "/api/lab/lab_shifts": {"app_name": "pro_laboratory", "model_name": "LabShift"},
    "/api/lab/lab_working_days": {"app_name": "pro_laboratory", "model_name": "LabWorkingDays"},
    "/api/lab/lab_blood_group": {"app_name": "pro_laboratory", "model_name": "LabBloodGroup"},
    "/api/lab/lab_marital_status": {"app_name": "pro_laboratory", "model_name": "LabMaritalStatus"},
    "/api/lab/bodyparts": {"app_name": "pro_laboratory", "model_name": "BodyParts"},
    "/api/lab/lab_technicians": {"app_name": "pro_laboratory", "model_name": "LabTechnicians"},
    "/api/lab/lab_technician_remarks": {"app_name": "pro_laboratory", "model_name": "LabTechnicianRemarks"},
    "/api/lab/lab_patient_word_report_templates": {"app_name": "pro_laboratory", "model_name": "LabPatientWordReportTemplate"},
    "/api/lab/lab_word_report_templates": {"app_name": "pro_laboratory", "model_name": "LabWordReportTemplate"},
    "/api/lab/lab_fixed_parameters_report_templates": {"app_name": "pro_laboratory", "model_name": "LabFixedParametersReportTemplate"},
    "/api/lab/lab_patient_refunds": {"app_name": "pro_laboratory", "model_name": "LabPatientRefund"},
    "/api/lab/lab_discount_types": {"app_name": "pro_laboratory", "model_name": "LabDiscountType"},
    "/api/lab/lab_global_test_methodology": {"app_name": "pro_laboratory", "model_name": "Methodology"},
    "/api/lab/lab_phlebotomists": {"app_name": "pro_laboratory", "model_name": "LabPhlebotomist"},
    "/api/lab/labdoctors_types": {"app_name": "pro_laboratory", "model_name": "LabDoctorsType"},
    "/api/lab/generate_barcode_pdf": {"app_name": "pro_laboratory", "model_name": "GeneratesBarCode"},
    "/api/lab/print_patient_invoice": {"app_name": "pro_laboratory", "model_name": "PrintsInvoice"},
    "/api/lab/print_patient_receipt": {"app_name": "pro_laboratory", "model_name": "PrintsReceipt"},
    "/api/lab/print_patient_test_report": {"app_name": "pro_laboratory", "model_name": "PrintsTestReport"},
    "/api/lab/generate_receipt": {"app_name": "pro_laboratory", "model_name": "LabPatientReceipts"},
    "/api/lab/lab_staff_access": {"app_name": "pro_laboratory", "model_name": "LabStaff"},
    "/api/lab/lab_patient_report_generate": {"app_name": "pro_laboratory", "model_name": "LabPatientFixedReportTemplateLabPatientWordReportTemplate"},
    "/api/lab/lab_fixed_patient_report_list": {"app_name": "pro_laboratory", "model_name": "LabPatientFixedReportTemplate"},
    "/api/lab/lab_fixed_patient_report_update": {"app_name": "pro_laboratory", "model_name": "LabPatientFixedReportTemplate"},
    "/api/lab/lab_word_patient_report_list": {"app_name": "pro_laboratory", "model_name": "LabPatientWordReportTemplate"},
    "/api/lab/print_test_report": {"app_name": "pro_laboratory", "model_name": "PrintsTestReport"},
    "/api/lab/lab_staff_role": {"app_name": "pro_laboratory", "model_name": "LabStaffRole"},
    "/api/lab/lab_doctor_role": {"app_name": "pro_laboratory", "model_name": "LabDoctorRole"},
    "/api/lab/lab_menu_access_for_staff": {"app_name": "pro_laboratory", "model_name": "LabMenuAccess"},
    "/api/lab/lab_staff_role_permissions": {"app_name": "pro_laboratory", "model_name": "LabStaffRolePermissions"},
    "/api/lab/lab_staff_login_access_action": {"app_name": "pro_laboratory", "model_name": "LabStaffLoginAccess"},
    "/api/lab/tpa_ultrasound_config": {"app_name": "pro_laboratory", "model_name": "TpaUltrasoundConfig"},
    "/api/lab/tpa_ultrasound_images": {"app_name": "pro_laboratory", "model_name": "TpaUltrasoundImages"},
    "/api/lab/tpa_ultrasound": {"app_name": "pro_laboratory", "model_name": "TpaUltrasound"},
    "/api/lab/print_receptionist_report": {"app_name": "pro_laboratory", "model_name": "PrintUserCollectionReports"},
    "/api/lab/patient_pndt": {"app_name": "pro_laboratory", "model_name": "PNDTResults"},
    "/api/lab/print_patient_pndt": {"app_name": "pro_laboratory", "model_name": "PrintsPNDTForm"},
    "/api/lab/referral_doctor_report": {"app_name": "pro_laboratory", "model_name": "PrintReferralDoctorReport"},
    "/api/lab/sync_referral_doctor_data": {"app_name": "pro_laboratory", "model_name": "ReferralAmountForDoctor"},
    "/api/lab/merging_referral_doctors": {"app_name": "pro_laboratory", "model_name": "LabDoctors(Referral)"},

    "/api/lab/print_template_types": {"app_name": "pro_laboratory", "model_name": "PrintTemplateType"},
    "/api/lab/print_templates": {"app_name": "pro_laboratory", "model_name": "PrintTemplate"},
    "/api/lab/print_data_templates": {"app_name": "pro_laboratory", "model_name": "PrintDataTemplate"},
    "/api/lab/preview_lab_technicians": {"app_name": "pro_laboratory", "model_name": "PreviewLabTechnicians"},
    "/api/lab/lab_word_patient_preview_report_list": {"app_name": "pro_laboratory", "model_name": "PreviewLabPatientWordReportTemplate"},
    "/api/lab/print_test_preview_report": {"app_name": "pro_laboratory", "model_name": "PreviewTestReport"},
    "/api/lab/download_patient_receipt": {"app_name": "pro_laboratory", "model_name": "DownloadPatientReceipt"},
    "/api/lab/download_test_report": {"app_name": "pro_laboratory", "model_name": "DownloadPatientTestReport"},
    "/api/lab/otp_for_report": {"app_name": "pro_laboratory", "model_name": "OTPForDownloadingPDF"},
    "/api/lab/resend_otp_for_report": {"app_name": "pro_laboratory", "model_name": "ResendOTPForDownloadingPDF"},
    "/api/lab/dashboard_settings": {"app_name": "pro_laboratory", "model_name": "DashBoardSettings"},
    "/api/lab/b_subscription_details_of_client": {"app_name": "pro_laboratory", "model_name": "BusinessSubscriptionDetailsOfClient"},
    "/api/lab/b_subscription_billing_invoice_of_client": {"app_name": "pro_laboratory", "model_name": "BusinessSubscriptionBillingInvoiceOfClient"},
    "/api/lab/generate_billing_invoice_of_client": {"app_name": "pro_laboratory", "model_name": "BusinessSubscriptionBillingInvoiceOfClient"},
    "/api/lab/doctor_access": {"app_name": "pro_laboratory", "model_name": "DoctorAccess"},
    "/api/lab/print_doctor_shared_report": {"app_name": "pro_laboratory", "model_name": "DoctorSharedTestReport"},
    "/api/lab/letterhead_settings": {"app_name": "pro_laboratory", "model_name": "LetterHeadSettings"},
    "/api/lab/business_data_status": {"app_name": "pro_laboratory", "model_name": "BusinessDataStatus"},
    "/api/lab/copy_biz_data": {"app_name": "pro_laboratory", "model_name": "CopiedLabDepartmentsData"},
    "/api/lab/user_permissions_access": {"app_name": "pro_laboratory", "model_name": "UserPermissionsAccess"},
    "/api/lab/business_discount_settings": {"app_name": "pro_laboratory", "model_name": "BusinessDiscountSettings"},
    "/api/lab/business_paid_amount_settings": {"app_name": "pro_laboratory", "model_name": "BusinessPaidAmountSettings"},
    "/api/lab/business_pndt_details": {"app_name": "pro_laboratory", "model_name": "BusinessPNDTDetails"},
    "/api/lab/print_report_settings": {"app_name": "pro_laboratory", "model_name": "PrintReportSettings"},
    "/api/lab/business_print_due_reports": {"app_name": "pro_laboratory", "model_name": "PrintDueReports"},
    "/api/lab/search_doctors": {"app_name": "pro_laboratory", "model_name": "LabDoctors"},
    "/api/lab/search_labtests": {"app_name": "pro_laboratory", "model_name": "LabGlobalTests"},
    "/api/lab/patients_standard_view": {"app_name": "pro_laboratory", "model_name": "Patient"},
    "/api/lab/master_search": {"app_name": "pro_laboratory", "model_name": "LabDoctors/Patient/LabGlobalTests"},
    "/api/lab/tests_master_search": {"app_name": "pro_laboratory", "model_name": "LabGlobalTests/LabGlobalPackages"},
    "/api/lab/manage_payments": {"app_name": "pro_laboratory", "model_name": "Patient"},
    "/api/lab/lab_phlebotomists_list": {"app_name": "pro_laboratory", "model_name": "LabPhlebotomist"},
    "/api/lab/lab_technicians_list": {"app_name": "pro_laboratory", "model_name": "LabTechnicians"},
    "/api/lab/lab_nabl": {"app_name": "pro_laboratory", "model_name": "LabPatientTests"},
    "/api/lab/lab_doctor_authorization": {"app_name": "pro_laboratory", "model_name": "LabDrAuthorization"},
    "/api/lab/lab_patient_receipts": {"app_name": "pro_laboratory", "model_name": "LabPatientReceipts"},
    "/api/lab/lab_patient_get_refund": {"app_name": "pro_laboratory", "model_name": "LabPatientRefund"},
    "/api/lab/lab_patient_get_invoice": {"app_name": "pro_laboratory", "model_name": "LabPatientInvoice"},
    "/api/lab/analytics_referral_doctor_details": {"app_name": "pro_laboratory", "model_name": "ReferralDoctorAnalytics"},
    "/api/lab/analytics_top_tests": {"app_name": "pro_laboratory", "model_name": "LabPatientTests"},
    "/api/lab/analytics_patient_overview": {"app_name": "pro_laboratory", "model_name": "Patient"},
    "/api/lab/phlebotomist_analytics": {"app_name": "pro_laboratory", "model_name": "LabPhlebotomist"},
    "/api/lab/technicians_analytics": {"app_name": "pro_laboratory", "model_name": "LabTechnicians"},
    "/api/lab/department_analytics": {"app_name": "pro_laboratory", "model_name": "LabPatientTests"},
    "/api/lab/business_status_analytics": {"app_name": "pro_laboratory", "model_name": "LabPatientInvoice"},
    "/api/lab/lab_patient_test_fixed_report_delete": {"app_name": "pro_laboratory", "model_name": "LabPatientFixedReportTemplate"},
    "/api/lab/doctor_authorization_analytics": {"app_name": "pro_laboratory", "model_name": "LabDrAuthorization"},
    "/api/lab/patient_registration_overview": {"app_name": "pro_laboratory", "model_name": "Patient"},
    "/api/lab/paymode_analytics": {"app_name": "pro_laboratory", "model_name": "LabPatientReceipts"},
    "/api/lab/patient_analytics": {"app_name": "pro_laboratory", "model_name": "Patient"},
    "/api/lab/lab_get_packages": {"app_name": "pro_laboratory", "model_name": "LabPatientPackages"},
    "/api/lab/lab_get_consulting_doctors": {"app_name": "pro_laboratory", "model_name": "LabDoctors"},
    "/api/lab/lab_get_referral_doctors": {"app_name": "pro_laboratory", "model_name": "LabDoctors"},
    "/api/lab/lab_consultant_doctor_stats": {"app_name": "pro_laboratory", "model_name": "LabDoctors"},
    "/api/lab/lab_referral_doctor_stats": {"app_name": "pro_laboratory", "model_name": "LabDoctors"},
    "/api/lab/tpa_ultrasound_integration": {"app_name": "pro_laboratory", "model_name": "TpaUltrasound"},
    "/api/lab/tpa_meta_info": {"app_name": "pro_laboratory", "model_name": "TpaUltrasound"},
    "/api/lab/tpa_machine_integration": {"app_name": "pro_laboratory", "model_name": "MachineIntegrationModel"},
    "/api/lab/user_collection_reports_list": {"app_name": "pro_laboratory", "model_name": "PrintTemplate"},
    "/api/lab/lab_departments_list_to_copy": {"app_name": "pro_laboratory", "model_name": "LabDepartments"},
    "/api/lab/lab_appointment_for_patient": {"app_name": "pro_laboratory", "model_name": "LabAppointmentForPatient"},


    #pro-universal data
    "/api/pro_u_data/lab_gender": {"app_name": "pro_universal_data", "model_name": "ULabPatientGender"},
    "/api/pro_u_data/lab_staff_gender": {"app_name": "pro_universal_data", "model_name": "ULabStaffGender"},
    "/api/pro_u_data/lab_patient_titles": {"app_name": "pro_universal_data", "model_name": "ULabPatientTitles"},
    "/api/pro_u_data/lab_patient_attender_titles": {"app_name": "pro_universal_data", "model_name": "ULabPatientAttenderTitles"},
    "/api/pro_u_data/ulab_patient_action": {"app_name": "pro_universal_data", "model_name": "ULabPatientAction"},
    "/api/pro_u_data/lab_departments": {"app_name": "pro_universal_data", "model_name": "ULabDepartments"},
    "/api/pro_u_data/lab_tests_status": {"app_name": "pro_universal_data", "model_name": "ULabTestStatus"},
    "/api/pro_u_data/ulab_print_template_data": {"app_name": "pro_universal_data", "model_name": "ULabPrintTemplateData"},
    "/api/pro_u_data/ulab_payment_mode_types": {"app_name": "pro_universal_data", "model_name": "ULabPaymentModeType"},
    "/api/pro_u_data/ulab_patient_ages": {"app_name": "pro_universal_data", "model_name": "ULabPatientAge"},
    "/api/pro_u_data/ulab_global_tests": {"app_name": "pro_universal_data", "model_name": "ULabGlobalTests"},
    "/api/pro_u_data/print_template_types": {"app_name": "pro_universal_data", "model_name": "PrintTemplateType"},
    "/api/pro_u_data/dashboard_options": {"app_name": "pro_universal_data", "model_name": "DashBoardOptions"},
    "/api/pro_u_data/doctor_reports": {"app_name": "pro_universal_data", "model_name": "DoctorSharedReport"},
    "/api/pro_u_data/department_flow_type": {"app_name": "pro_universal_data", "model_name": "DepartmentFlowType"},
    "/api/pro_u_data/user_permissions": {"app_name": "pro_universal_data", "model_name": "UserPermissions"},

    "/api/pro_u_data/lab_menus_list": {"app_name": "pro_universal_data", "model_name": "ULabMenus"},
    "/api/pro_u_data/lab_report_types": {"app_name": "pro_universal_data", "model_name": "ULabReportType"},
    "/api/pro_u_data/get_template_tags": {"app_name": "pro_universal_data", "model_name": "Tag"},

    "/api/pro_u_data/user_collection_reports_list": {"app_name": "pro_universal_data", "model_name": "PrintTemplate"},
    "/api/pro_u_data/messaging_service_types": {"app_name": "pro_universal_data", "model_name": "MessagingServiceTypes"},
    "/api/pro_u_data/messaging_vendors": {"app_name": "pro_universal_data", "model_name": "MessagingVendors"},
    "/api/pro_u_data/messaging_send_type": {"app_name": "pro_universal_data", "model_name": "MessagingSendType"},
    "/api/pro_u_data/messaging_logs": {"app_name": "pro_universal_data", "model_name": "MessagingLogs"},
    "/api/pro_u_data/messaging_category": {"app_name": "pro_universal_data", "model_name": "MessagingCategory"},
    "/api/pro_u_data/messaging_templates": {"app_name": "pro_universal_data", "model_name": "MessagingTemplates"},
    "/api/pro_u_data/messaging_for": {"app_name": "pro_universal_data", "model_name": "MessagingFor"},
    "/api/pro_u_data/send_and_save_sms": {"app_name": "pro_universal_data", "model_name": "SendSMSData"},
    "/api/pro_u_data/create_tags": {"app_name": "pro_universal_data", "model_name": "Tag"},
    "/api/pro_u_data/send_and_save_whatsapp_sms": {"app_name": "pro_universal_data", "model_name": "SendAndSaveWhatsAppSMSData"},
    "/api/pro_u_data/initiate_payment": {"app_name": "pro_universal_data", "model_name": "InitiatePaymentPayment"},
    "/api/pro_u_data/payment_callback": {"app_name": "pro_universal_data", "model_name": "PaymentCallback"},



    }
