# Generated by Django 5.0.2 on 2025-01-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmastock',
            name='over_all_tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
