# Generated by Django 5.0.2 on 2024-12-25 23:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('healtho_pro_user', '0001_initial'),
        ('pro_universal_data', '0001_initial'),
        ('super_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmodules',
            name='modules',
            field=models.ManyToManyField(blank=True, to='pro_universal_data.ulabmenus'),
        ),
        migrations.AddField(
            model_name='businessprofiles',
            name='pro_user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessmodules',
            name='business',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='businessaddresses',
            name='b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='bexecutive',
            name='b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='bcontacts',
            name='b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='businessprofilesimages',
            name='b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='images', to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='businesssubscriptionplans',
            name='calculation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessbillcalculationtype'),
        ),
        migrations.AddField(
            model_name='businesssubscriptionplans',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesssubscriptionplans',
            name='last_updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businesssubscriptionplans',
            name='modules',
            field=models.ManyToManyField(blank=True, to='pro_universal_data.ulabmenus'),
        ),
        migrations.AddField(
            model_name='businesssubscriptionplans',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businesssubscriptiontype'),
        ),
        migrations.AddField(
            model_name='businessbillcalculationtype',
            name='subscription_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businesssubscriptiontype'),
        ),
        migrations.AddField(
            model_name='businesstimings',
            name='b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_timings', to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='businesstimings',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessworkingdays'),
        ),
        migrations.AddField(
            model_name='businessprofiles',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.city'),
        ),
        migrations.AddField(
            model_name='healthoprouser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.city'),
        ),
        migrations.AddField(
            model_name='businessprofiles',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.country'),
        ),
        migrations.AddField(
            model_name='healthoprouser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.country'),
        ),
        migrations.AddField(
            model_name='deletedbusinessprofiles',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.city'),
        ),
        migrations.AddField(
            model_name='deletedbusinessprofiles',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.country'),
        ),
        migrations.AddField(
            model_name='deletedbusinessprofiles',
            name='deleted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='super_admin.healthoprosuperadmin'),
        ),
        migrations.AddField(
            model_name='domain',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='globalbusinesssettings',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='globalbusinesssettings',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalmessagingsettings',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='globalmessagingsettings',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.messagingservicetypes'),
        ),
        migrations.AddField(
            model_name='deletedbusinessprofiles',
            name='provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.healthcareregistrytype'),
        ),
        migrations.AddField(
            model_name='businessprofiles',
            name='provider_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.healthcareregistrytype'),
        ),
        migrations.AddField(
            model_name='healthoprouser',
            name='HealthcareRegistryType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.healthcareregistrytype'),
        ),
        migrations.AddField(
            model_name='healthopromessaginguser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='healthopromessaginguser',
            name='pro_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='otp',
            name='pro_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overallbusinesssubscriptionplanspurchased',
            name='b_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='overallbusinesssubscriptionstatus',
            name='b_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='prodoctor',
            name='pro_user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodoctorappointmentslot',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='prodoctorappointmentslot',
            name='pro_doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointment_slots', to='healtho_pro_user.prodoctor'),
        ),
        migrations.AddField(
            model_name='prodoctorawardsrecognitions',
            name='pro_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodoctorconsultation',
            name='consultation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.consultation'),
        ),
        migrations.AddField(
            model_name='prodoctorconsultation',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.businessprofiles'),
        ),
        migrations.AddField(
            model_name='prodoctorconsultation',
            name='pro_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation', to='healtho_pro_user.prodoctor'),
        ),
        migrations.AddField(
            model_name='prodoctorappointmentslot',
            name='consultation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.prodoctorconsultation'),
        ),
        migrations.AddField(
            model_name='prodoctorprofessionaldetails',
            name='awards_and_recognitions',
            field=models.ManyToManyField(blank=True, to='healtho_pro_user.prodoctorawardsrecognitions'),
        ),
        migrations.AddField(
            model_name='prodoctorprofessionaldetails',
            name='languages_spoken',
            field=models.ManyToManyField(blank=True, to='healtho_pro_user.prodoctorlanguagespoken'),
        ),
        migrations.AddField(
            model_name='prodoctorprofessionaldetails',
            name='pro_doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_details', to='healtho_pro_user.prodoctor'),
        ),
        migrations.AddField(
            model_name='prodoctorrecognitionsimages',
            name='ProDoctorAwardsRecognitionsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proDoctorsRecognitionImages', to='healtho_pro_user.prodoctorawardsrecognitions'),
        ),
        migrations.AddField(
            model_name='prodoctorresearchpublications',
            name='pro_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prodoctorresearchpublicationsimages',
            name='ProDoctorResearchPublicationsID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proDoctorsRecognitionImages', to='healtho_pro_user.prodoctorresearchpublications'),
        ),
        migrations.AddField(
            model_name='prodoctorprofessionaldetails',
            name='research_and_publications',
            field=models.ManyToManyField(blank=True, to='healtho_pro_user.prodoctorresearchpublicationsimages'),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healtho_pro_user.country'),
        ),
        migrations.AddField(
            model_name='deletedbusinessprofiles',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healtho_pro_user.state'),
        ),
        migrations.AddField(
            model_name='businessprofiles',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.state'),
        ),
        migrations.AddField(
            model_name='healthoprouser',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.state'),
        ),
        migrations.AddField(
            model_name='prodoctorprofessionaldetails',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.uprodoctorspecializations'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='pro_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='usertenant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='healthoprouser',
            name='user_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.usertype'),
        ),
    ]
