# Generated by Django 5.0.2 on 2024-12-31 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healtho_pro_user', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='url',
            field=models.CharField(blank=True, default='https://healtho.pro/', max_length=253, null=True),
        ),
    ]
