# Generated by Django 5.0.2 on 2024-12-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('pro_laboratory', '0001_initial'),
        ('pro_universal_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labexpenses',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labexpenses',
            name='pay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpaymentmodetype'),
        ),
        migrations.AddField(
            model_name='labexpenses',
            name='expense_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.labexpensetype'),
        ),
        migrations.AddField(
            model_name='labincomes',
            name='authorized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='authorized_incomes', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labincomes',
            name='pay_mode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabpaymentmodetype'),
        ),
        migrations.AddField(
            model_name='labincomes',
            name='received_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_incomes', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labincomes',
            name='income_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.labincometype'),
        ),
        migrations.AddField(
            model_name='labexpenses',
            name='paid_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.labpaidtotype'),
        ),
        migrations.AddField(
            model_name='labincomes',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.labtoaccounttype'),
        ),
        migrations.AddField(
            model_name='labexpenses',
            name='to_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.labtoaccounttype'),
        ),
    ]
