# Generated by Django 5.0.2 on 2025-01-15 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('pro_laboratory', '0014_labfixedparametersreporttemplate_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labexpenses',
            name='to_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.labtoaccounttype'),
        ),
        migrations.AlterField(
            model_name='labincomes',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_incomes', to='pro_laboratory.labstaff'),
        ),
    ]
