# Generated by Django 5.0.2 on 2025-01-16 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_labexpenses_to_account_and_more'),
        ('pro_laboratory', '0014_labfixedparametersreporttemplate_display_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labexpenses',
            old_name='voucher_id',
            new_name='invoice_no',
        ),
        migrations.AddField(
            model_name='labexpenses',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_expenses', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='labincomes',
            name='account_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_incomes', to='pro_laboratory.labstaff'),
        ),
    ]
