# Generated by Django 5.0.2 on 2025-01-16 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_voucher_id_labexpenses_invoice_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labexpenses',
            old_name='expense_id',
            new_name='voucher_id',
        ),
    ]
