# Generated by Django 5.0.2 on 2025-01-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_expense_id_labexpenses_voucher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labexpenses',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='labincomes',
            name='received_by',
        ),
        migrations.RemoveField(
            model_name='labincomes',
            name='to_account',
        ),
        migrations.AddField(
            model_name='labincomes',
            name='received_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_incomes', to='accounts.labtoaccounttype'),
        ),
    ]
