# Generated by Django 5.0.2 on 2025-01-16 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_labexpenses_to_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LabToAccountType',
            new_name='LabIncomeFromAccount',
        ),
    ]
