from . import doctors_views
from . import global_views
from . import patient_views
from . import search_query_views
from . import universal_views
from . import pndt_views
from . import doctorAuthorization_views
from . import testPackages_views
from . import sourcing_lab_views
from . import messaging_views
from . import bulk_messaging_views
from . import b2b_views
from . import dashboard_views