# Generated by Django 5.0.2 on 2024-12-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cloud_messaging', '0001_initial'),
        ('healtho_pro_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='initiator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convo_starter', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convo_participant', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='group',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='cloud_messaging_group_admin', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='group',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='group_creator', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(blank=True, to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='cloud_messaging.conversation'),
        ),
        migrations.AddField(
            model_name='message',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='cloud_messaging.group'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='message_sender', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloud_messaging.message'),
        ),
        migrations.AddField(
            model_name='messagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='cloud_messaging.messagingfile'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('initiator', 'receiver')},
        ),
        migrations.AlterUniqueTogether(
            name='messagereadstatus',
            unique_together={('user', 'message')},
        ),
    ]
