# Generated by Django 5.0.2 on 2024-12-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business_messaging', '0001_initial'),
        ('cloud_messaging', '0001_initial'),
        ('healtho_pro_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessgroup',
            name='admin',
            field=models.ManyToManyField(blank=True, related_name='client_group_admin', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='healtho_pro_user.client'),
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_group_creator', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='businessgroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='client_group_members', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='businessmessage',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_messages', to='cloud_messaging.conversation'),
        ),
        migrations.AddField(
            model_name='businessmessage',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='messages', to='business_messaging.businessgroup'),
        ),
        migrations.AddField(
            model_name='businessmessage',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_message_sender', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='businessmessagereadstatus',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business_messaging.businessmessage'),
        ),
        migrations.AddField(
            model_name='businessmessagereadstatus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_user', to='healtho_pro_user.healthopromessaginguser'),
        ),
        migrations.AddField(
            model_name='businessmessage',
            name='attachment',
            field=models.ManyToManyField(blank=True, to='business_messaging.businessmessagingfile'),
        ),
        migrations.AlterUniqueTogether(
            name='businessmessagereadstatus',
            unique_together={('user', 'message')},
        ),
    ]
