# Generated by Django 5.0.2 on 2024-12-25 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pro_hospital', '0001_initial'),
        ('pro_laboratory', '0001_initial'),
        ('pro_pharmacy', '0001_initial'),
        ('pro_universal_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorconsultationdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='doctorconsultationdetails',
            name='labdoctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdoctors'),
        ),
        migrations.AddField(
            model_name='doctorconsultationdetails',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_consultation_fee_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='globalpackageconsultation',
            name='consultation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.doctorconsultationdetails'),
        ),
        migrations.AddField(
            model_name='globalpackagelabtest',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='globalpackages',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='globalpackageroom',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_rooms', to='pro_hospital.globalpackages'),
        ),
        migrations.AddField(
            model_name='globalpackagelabtest',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_lab_tests', to='pro_hospital.globalpackages'),
        ),
        migrations.AddField(
            model_name='globalpackageconsultation',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_consultations', to='pro_hospital.globalpackages'),
        ),
        migrations.AddField(
            model_name='globalpackageservice',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='package_services', to='pro_hospital.globalpackages'),
        ),
        migrations.AddField(
            model_name='globalroom',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.floor'),
        ),
        migrations.AddField(
            model_name='globalroom',
            name='time_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.timecategory'),
        ),
        migrations.AddField(
            model_name='globalpackageroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalroom'),
        ),
        migrations.AddField(
            model_name='globalroombeds',
            name='global_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalroom'),
        ),
        migrations.AddField(
            model_name='globalroombeds',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='globalservices',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='globalservices',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdepartments'),
        ),
        migrations.AddField(
            model_name='globalservices',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='global_service_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='globalpackageservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalservices'),
        ),
        migrations.AddField(
            model_name='investigationsinprescription',
            name='packages',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labglobalpackages'),
        ),
        migrations.AddField(
            model_name='investigationsinprescription',
            name='tests',
            field=models.ManyToManyField(blank=True, to='pro_laboratory.labglobaltests'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='GlobalRoomId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalroom'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='booked_bed_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalroombeds'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.floor'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='time_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.timecategory'),
        ),
        migrations.AddField(
            model_name='medicinesinprescription',
            name='in_take_time',
            field=models.ManyToManyField(blank=True, to='pro_universal_data.universaldaytimeperiod'),
        ),
        migrations.AddField(
            model_name='medicinesinprescription',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_pharmacy.pharmaitems'),
        ),
        migrations.AddField(
            model_name='medicinesinprescription',
            name='when_to_take',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.universalfoodintake'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='case_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.casetype'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.doctorconsultationdetails'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_appointment_consultation_details_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabteststatus'),
        ),
        migrations.AddField(
            model_name='patientpackages',
            name='GlobalPackageId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalpackages'),
        ),
        migrations.AddField(
            model_name='patientpackages',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patientpackages',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='patientdoctorconsultationdetails',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientpackages'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientpackages'),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='ailments',
            field=models.ManyToManyField(blank=True, to='pro_universal_data.universalailments'),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labdoctors'),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='doctor_consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientdoctorconsultationdetails'),
        ),
        migrations.AddField(
            model_name='patientprescription',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='medicinesinprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientprescription'),
        ),
        migrations.AddField(
            model_name='investigationsinprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientprescription'),
        ),
        migrations.AddField(
            model_name='patientservices',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patientservices',
            name='last_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='patient_service_last_updated_by', to='pro_laboratory.labstaff'),
        ),
        migrations.AddField(
            model_name='patientservices',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientpackages'),
        ),
        migrations.AddField(
            model_name='patientservices',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
        migrations.AddField(
            model_name='patientservices',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.globalservices'),
        ),
        migrations.AddField(
            model_name='patientservices',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_universal_data.ulabteststatus'),
        ),
        migrations.AddField(
            model_name='iproombooking',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.roomtype'),
        ),
        migrations.AddField(
            model_name='globalroom',
            name='room_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.roomtype'),
        ),
        migrations.AddField(
            model_name='vehiclebasicinfo',
            name='driver',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_driver', to='pro_hospital.driver'),
        ),
        migrations.AddField(
            model_name='vehiclebasicinfo',
            name='vehicle',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ambulance_vehicle', to='pro_hospital.vehicle'),
        ),
        migrations.AddField(
            model_name='ambulancedetails',
            name='vehicle_basic_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_basic_details', to='pro_hospital.vehiclebasicinfo'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pro_hospital.vehicletype'),
        ),
        migrations.AddField(
            model_name='vitalsinprescription',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_hospital.patientprescription'),
        ),
    ]
