# Generated by Django 5.0.2 on 2024-12-27 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_hospital', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iproombooking',
            name='admitted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
