# Generated by Django 5.0.2 on 2024-12-27 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_hospital', '0003_iproombooking_admitted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientservices',
            name='added_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
