# Generated by Django 5.0.2 on 2024-12-30 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_hospital', '0004_alter_patientservices_added_on'),
        ('pro_laboratory', '0004_labpatienttests_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp1', models.CharField(blank=True, null=True)),
                ('bp2', models.CharField(blank=True, null=True)),
                ('pulse', models.CharField(blank=True, null=True)),
                ('height', models.CharField(blank=True, null=True)),
                ('weight', models.CharField(blank=True, null=True)),
                ('spo2', models.CharField(blank=True, null=True)),
                ('temperature', models.CharField(blank=True, null=True)),
                ('grbs', models.CharField(blank=True, max_length=100, null=True)),
                ('added_on', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient')),
            ],
        ),
    ]
