# Generated by Django 5.0.2 on 2024-12-30 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_hospital', '0005_patientvitals'),
        ('pro_laboratory', '0004_labpatienttests_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientvitals',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.labstaff'),
        ),
        migrations.AlterField(
            model_name='patientvitals',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pro_laboratory.patient'),
        ),
    ]
